# Generated by Django 2.2.6 on 2019-10-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.IntegerField()),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grandbackend.AppUser')),
            ],
        ),
    ]
