# Generated by Django 2.2.6 on 2019-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandbackend', '0002_appuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='activityLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuserprofile',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuserprofile',
            name='usersGoal',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuserprofile',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
