# Generated by Django 2.2.6 on 2019-11-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandbackend', '0004_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_time', models.CharField(max_length=128)),
                ('rating', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandbackend.FoodItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandbackend.AppUser')),
            ],
        ),
    ]
